# Generated by Django 3.1.5 on 2022-03-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmpost', '0003_auto_20220313_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamodel',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
